In [2]:
import pandas as pd
df=pd.read_csv("./CSV/Banana Green.csv")
print(df.head())

   Sl no. District Name                    Market Name       Commodity  \
0       1    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green
1       2    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green
2       3    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green
3       4    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green
4       5    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green

          Variety  Grade  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  \
0  Banana - Green  Local                   2000.0                     2500
1  Banana - Green  Local                   2000.0                     2500
2  Banana - Green  Local                   2000.0                     2500
3  Banana - Green  Local                   2000.0                     2500
4  Banana - Green  Local                   2000.0                     2500

   Modal Price (Rs./Quintal)   Price Date
0                       2500  01 Oct 2024
1                       2500  24 Dec 2024
2                       2500  30 Dec 2024
3                       2500  30 Sep 2024
4                       2500  31 Dec 2024

In [3]:
print(df.isnull().sum())

Sl no.                       0
District Name                0
Market Name                  0
Commodity                    0
Variety                      0
Grade                        0
Min Price (Rs./Quintal)      0
Max Price (Rs./Quintal)      0
Modal Price (Rs./Quintal)    0
Price Date                   0
dtype: int64

In [4]:
df['Price Date'] = pd.to_datetime(df['Price Date'])
print(df.head())

   Sl no. District Name                    Market Name       Commodity  \
0       1    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green
1       2    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green
2       3    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green
3       4    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green
4       5    Dharmapuri  AJattihalli(Uzhavar Sandhai )  Banana - Green

          Variety  Grade  Min Price (Rs./Quintal)  Max Price (Rs./Quintal)  \
0  Banana - Green  Local                   2000.0                     2500
1  Banana - Green  Local                   2000.0                     2500
2  Banana - Green  Local                   2000.0                     2500
3  Banana - Green  Local                   2000.0                     2500
4  Banana - Green  Local                   2000.0                     2500

   Modal Price (Rs./Quintal) Price Date
0                       2500 2024-10-01
1                       2500 2024-12-24
2                       2500 2024-12-30
3                       2500 2024-09-30
4                       2500 2024-12-31

In [9]:
df['Market Name'] = df['Market Name'].str.strip()
df['Market Name'] = df['Market Name'].str.replace('Uzhavar Sandhai ','Farmers Market')
print(df['Market Name'].unique())

['AJattihalli(Farmers Market)' 'Alangudi' 'Alangudi(Farmers Market)'
 'Ambasamudram' 'Ambasamudram(Farmers Market)' 'Ambattur(Farmers Market)'
 'Ammapet(Farmers Market)' 'Anaiyur(Farmers Market)'
 'Andipatti(Farmers Market)' 'Anna nagar(Farmers Market)' 'Annur' 'Arani'
 'Arani(Farmers Market)' 'Aranthangi' 'Aranthangi(Farmers Market)' 'Arcot'
 'Arcot(Farmers Market)' 'Ariyalur(Uzhavar Sandhai)'
 'Aruppukottai(Farmers Market)' 'Arur' 'Athur(Farmers Market)'
 'Attayampatti(Farmers Market)' 'Attur' 'Avallapalli(Farmers Market)'
 'Bodinayakanur(Farmers Market)' 'Bodinayakkanur' 'Chengalpattu'
 'Chengalpet(Farmers Market)' 'Chengam' 'Chengam(Farmers Market)'
 'Cheyyar' 'Cheyyar(Farmers Market)' 'Chidambaram'
 'Chidambaram(Farmers Market)' 'Chinnalapatti(Farmers Market)'
 'Chinnamanur' 'Chinnamanur(Farmers Market)' 'Chokkikulam(Farmers Market)'
 'Coonoor(Farmers Market)' 'Cuddalore' 'Cuddalore(Farmers Market)'
 'Cumbum' 'Denkanikottai' 'Denkanikottai(Farmers Market)' 'Devakottai'
 'Devakottai (Farmers Market)' 'Devaram(Farmers Market)' 'Dharampuri'
 'Dharapuram' 'Dharapuram(Farmers Market)' 'Dharmapuri(Farmers Market)'
 'Dindigul' 'Dindigul(Farmers Market)' 'Edapadi (Farmers Market)'
 'Edappadi' 'Elampillai(Farmers Market)' 'Gandarvakottai(Farmers Market)'
 'Gingee' 'Gingee(Farmers Market)' 'Gobichettipalayam'
 'Gobichettipalayam(Farmers Market)' 'Gudalur(Farmers Market)'
 'Gudiyatham' 'Gudiyatham(Farmers Market)' 'Guduvancheri(Farmers Market)'
 'Harur(Farmers Market)' 'Hasthampatti(Farmers Market)' 'Hosur'
 'Hosur(Farmers Market)' 'Jalagandapuram(Farmers Market)'
 'Jameenrayapettai(Farmers Market)' 'Jeyankondam (Farmers Market)'
 'Kahithapattarai(Farmers Market)' 'Kallakurichi'
 'Kallakurichi(Farmers Market)' 'Kambam(Farmers Market)'
 'Kancheepuram(Farmers Market)' 'Kanchipuram'
 'Kandiyaperi(Farmers Market)' 'Kangayam(Farmers Market)' 'Kangeyam'
 'Karaikudi' 'Karaikudi(Farmers Market)' 'Karambakkudi(Farmers Market)'
 'Kariyapatti(Farmers Market)' 'Karur' 'Karur(Farmers Market)'
 'Katpadi (Farmers Market)' 'Katpadi(Uzhavar Santhai)'
 'Kaveripattinam(Farmers Market)' 'Keelpennathur(Farmers Market)'
 'KKNagar(Farmers Market)' 'Kothagiri(Farmers Market)' 'Kovilpatti'
 'Kovilpatti(Farmers Market)' 'Krishnagiri' 'Krishnagiri(Farmers Market)'
 'Kulithalai(Farmers Market)' 'Kumarapalayam(Farmers Market)' 'Kumbakonam'
 'Kumbakonam (Farmers Market)' 'Kundrathur(Farmers Market)'
 'Kurichi(Farmers Market)' 'Lalgudi' 'Lalgudi(Farmers Market)'
 'Madhuranthagam(Farmers Market)' 'Mailaduthurai' 'Manachanallur'
 'Manachanallur(Farmers Market)' 'Manapparai' 'Manapparai(Farmers Market)'
 'Mannargudi' 'Mannargudi I(Farmers Market)'
 'Mannargudi II(Farmers Market)' 'Mannarkudi'
 'Mayiladuthurai(Farmers Market)' 'Medavakkam(Farmers Market)'
 'Melapalayam(Farmers Market)' 'Melur' 'Melur(Farmers Market)'
 'Mettupalayam(Farmers Market)' 'Mettur(Farmers Market)'
 'Mohanur(Farmers Market)' 'Musiri(Farmers Market)'
 'Muthupettai(Farmers Market)' 'Myladi(Farmers Market)' 'Nagapattinam'
 'Nagapattinam(Farmers Market)' 'Namakkal' 'Namakkal(Farmers Market)'
 'Nanganallur(Farmers Market)' 'Naravarikuppam(Farmers Market)'
 'Natrampalli(Farmers Market)' 'Needamangalam(Farmers Market)'
 'NGO Colony(Farmers Market)' 'Padappai(Farmers Market)'
 'Palacode(Farmers Market)' 'Palakode' 'Palanganatham(Farmers Market)'
 'Palani' 'Palani(Farmers Market)' 'Palayamkottai(Farmers Market)'
 'Palladam' 'Palladam(Farmers Market)' 'Pallapatti (Farmers Market)'
 'Pallavaram(Farmers Market)' 'Panruti' 'Panruti(Farmers Market)'
 'Papanasam' 'Papanasam(Farmers Market)' 'Paramakudi'
 'Paramakudi(Farmers Market)' 'Paramathivelur(Farmers Market)'
 'Paruthipattu(Farmers Market)' 'Pattukottai'
 'Pattukottai(Farmers Market)' 'Pennagaram' 'Pennagaram(Farmers Market)'
 'Perambakkam(Farmers Market)' 'Perambalur(Farmers Market)'
 'Periyakulam(Farmers Market)' 'Periyar Nagar(Farmers Market)'
 'Perundurai' 'Perundurai(Farmers Market)' 'Pollachi'
 'Pollachi(Farmers Market)' 'Polur(Thiruvannamalai)'
 'Polur(Farmers Market)' 'Pudukottai' 'Pudukottai(Farmers Market)'
 'Rajapalayam(Farmers Market)' 'Ramanathapuram(phase 3)'
 'Ramanathapuram(Farmers Market)' 'Ranipettai(Farmers Market)' 'Rasipuram'
 'Rasipuram(Farmers Market)' 'RSPuram(Farmers Market)'
 'Sampath Nagar(Farmers Market)' 'Sangarapuram'
 'Sankarankoil(Farmers Market)' 'Sankarankovil'
 'Sankarapuram(Farmers Market)' 'Sathiyamagalam(Farmers Market)' 'Sathur'
 'Sathur(Farmers Market)' 'Sathyamangalam' 'Singampunari(Farmers Market)'
 'Singampuneri' 'Singanallur(Farmers Market)' 'Sirkali'
 'Sirkali(Farmers Market)' 'Sivagangai' 'Sivagangai (Farmers Market)'
 'Sivakasi(Farmers Market)' 'Sooramangalam(Farmers Market)'
 'Srivilliputhur(Farmers Market)' 'Sulur' 'Sulur(Farmers Market)'
 'Sundarapuram(Farmers Market)' 'Sunguvarchatram(Farmers Market)'
 'Tamarainagar(Farmers Market)' 'Tenkasi(Farmers Market)' 'Thalavadi'
 'Thalavadi(Farmers Market)' 'Thalavaipuram(Farmers Market)' 'Thammampati'
 'Thammampatti (Farmers Market)' 'Thanjavur' 'Thanjavur(Farmers Market)'
 'Thathakapatti(Farmers Market)' 'Theni' 'Theni(Farmers Market)'
 'Thenkasi' 'Thirukalukundram(Farmers Market)' 'Thirupathur'
 'Thiruvannamalai' 'Thiruvarur' 'Thoothukudi' 'Thuraiyur' 'Tindivanam'
 'Tiruchengode' 'Tirupatthur(Farmers Market)'
 'Tiruppur (North) (Farmers Market)' 'Tiruppur (South) (Farmers Market)'
 'Tiruthuraipoondi' 'Tiruthuraipoondi(Farmers Market)'
 'Tiruvallur(Farmers Market)' 'Tiruvannamalai(Farmers Market)'
 'Tiruvarur(Farmers Market)' 'Tuticorin(Farmers Market)'
 'Udhagamandalam(Farmers Market)' 'Udumalpet' 'Ulundurpettai'
 'Usilampatty' 'Vadaseri' 'Vadavalli(Farmers Market)' 'Valangaiman'
 'Vandavasi(Farmers Market)' 'Vaniyambadi' 'Vaniyampadi(Farmers Market)'
 'Vedasanthur(Farmers Market)' 'Velayuthampalayam(Farmers Market)'
 'Vellore' 'Viralimalai(Farmers Market)' 'Virudhunagar'
 'Virudhunagar(Farmers Market)' 'Viruthachalam(Farmers Market)']

In [12]:
df.drop_duplicates()

,Sl no.,District Name,Market Name,Commodity,Variety,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date
0,1,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500,2500,2024-10-01
1,2,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500,2500,2024-12-24
2,3,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500,2500,2024-12-30
3,4,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500,2500,2024-09-30
4,5,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500,2500,2024-12-31
...,...,...,...,...,...,...,...,...,...,...
59908,59909,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,2500.0,2500,2500,2025-04-29
59909,59910,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,2500.0,2500,2500,2025-04-30
59910,59911,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,2500.0,2500,2500,2025-06-30
59911,59912,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,3500.0,3500,3500,2025-05-01
59912,59913,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,3500.0,3500,3500,2024-09-03

In [18]:
# TODO check if column can be dropped
df['Variety'].unique()

array(['Banana - Green'], dtype=object)

In [21]:
df['Day Of Week'] = df['Price Date'].dt.dayofweek
print(df)

       Sl no. District Name                    Market Name       Commodity  \
0           1    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
1           2    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
2           3    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
3           4    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
4           5    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
...       ...           ...                            ...             ...
59908   59909     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green
59909   59910     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green
59910   59911     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green
59911   59912     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green
59912   59913     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green

              Variety  Grade  Min Price (Rs./Quintal)  \
0      Banana - Green  Local                   2000.0
1      Banana - Green  Local                   2000.0
2      Banana - Green  Local                   2000.0
3      Banana - Green  Local                   2000.0
4      Banana - Green  Local                   2000.0
...               ...    ...                      ...
59908  Banana - Green  Local                   2500.0
59909  Banana - Green  Local                   2500.0
59910  Banana - Green  Local                   2500.0
59911  Banana - Green  Local                   3500.0
59912  Banana - Green  Local                   3500.0

       Max Price (Rs./Quintal)  Modal Price (Rs./Quintal) Price Date  \
0                         2500                       2500 2024-10-01
1                         2500                       2500 2024-12-24
2                         2500                       2500 2024-12-30
3                         2500                       2500 2024-09-30
4                         2500                       2500 2024-12-31
...                        ...                        ...        ...
59908                     2500                       2500 2025-04-29
59909                     2500                       2500 2025-04-30
59910                     2500                       2500 2025-06-30
59911                     3500                       3500 2025-05-01
59912                     3500                       3500 2024-09-03

       Day Of Week
0                1
1                1
2                0
3                0
4                1
...            ...
59908            1
59909            2
59910            0
59911            3
59912            1

[59913 rows x 11 columns]

In [29]:
# Check the data types of the price columns
df['Max Price (Rs./Quintal)'] = pd.to_numeric(df['Max Price (Rs./Quintal)'], errors='coerce').astype('float64')
df['Modal Price (Rs./Quintal)'] = pd.to_numeric(df['Modal Price (Rs./Quintal)'], errors='coerce').astype('float64')

print(df[['Min Price (Rs./Quintal)','Max Price (Rs./Quintal)', 'Modal Price (Rs./Quintal)']].dtypes)

Min Price (Rs./Quintal)      float64
Max Price (Rs./Quintal)      float64
Modal Price (Rs./Quintal)    float64
dtype: object

In [30]:
print(df)

       Sl no. District Name                    Market Name       Commodity  \
0           1    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
1           2    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
2           3    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
3           4    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
4           5    Dharmapuri    AJattihalli(Farmers Market)  Banana - Green
...       ...           ...                            ...             ...
59908   59909     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green
59909   59910     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green
59910   59911     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green
59911   59912     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green
59912   59913     Cuddalore  Viruthachalam(Farmers Market)  Banana - Green

              Variety  Grade  Min Price (Rs./Quintal)  \
0      Banana - Green  Local                   2000.0
1      Banana - Green  Local                   2000.0
2      Banana - Green  Local                   2000.0
3      Banana - Green  Local                   2000.0
4      Banana - Green  Local                   2000.0
...               ...    ...                      ...
59908  Banana - Green  Local                   2500.0
59909  Banana - Green  Local                   2500.0
59910  Banana - Green  Local                   2500.0
59911  Banana - Green  Local                   3500.0
59912  Banana - Green  Local                   3500.0

       Max Price (Rs./Quintal)  Modal Price (Rs./Quintal) Price Date  \
0                       2500.0                     2500.0 2024-10-01
1                       2500.0                     2500.0 2024-12-24
2                       2500.0                     2500.0 2024-12-30
3                       2500.0                     2500.0 2024-09-30
4                       2500.0                     2500.0 2024-12-31
...                        ...                        ...        ...
59908                   2500.0                     2500.0 2025-04-29
59909                   2500.0                     2500.0 2025-04-30
59910                   2500.0                     2500.0 2025-06-30
59911                   3500.0                     3500.0 2025-05-01
59912                   3500.0                     3500.0 2024-09-03

       Day Of Week
0                1
1                1
2                0
3                0
4                1
...            ...
59908            1
59909            2
59910            0
59911            3
59912            1

[59913 rows x 11 columns]

In [37]:
df = df.drop(columns="Sl no.")
df

,District Name,Market Name,Commodity,Variety,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,Day Of Week
0,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500.0,2500.0,2024-10-01,1
1,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500.0,2500.0,2024-12-24,1
2,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500.0,2500.0,2024-12-30,0
3,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500.0,2500.0,2024-09-30,0
4,Dharmapuri,AJattihalli(Farmers Market),Banana - Green,Banana - Green,Local,2000.0,2500.0,2500.0,2024-12-31,1
...,...,...,...,...,...,...,...,...,...,...
59908,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,2500.0,2500.0,2500.0,2025-04-29,1
59909,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,2500.0,2500.0,2500.0,2025-04-30,2
59910,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,2500.0,2500.0,2500.0,2025-06-30,0
59911,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,3500.0,3500.0,3500.0,2025-05-01,3
59912,Cuddalore,Viruthachalam(Farmers Market),Banana - Green,Banana - Green,Local,3500.0,3500.0,3500.0,2024-09-03,1

In [38]:
df.to_csv('./Cleaned CSVs/Banana - Green.csv', index=False)